### PR TITLE
Sample project that implements Reactive Extensions with NetMQ as the transport layer

### PR DESCRIPTION
**Pull request by sharpe5**
Attn: @drewnoakes @somdoron 

Just created a pull request that implements Reactive Extensions (RX) with NetMQ as the transport layer.

Eventually, this will live in its own NuGet package, e.g. `NetMQ.ReactiveExtensions`. The reason is that it depends on `RX` and `ProtoBuf`, and we don't want to drag these into `NetMQ core`.

The libary is very simple to use. With a couple of lines of code, we can send any RX stream between different processes or machines.

The API is a drop-in replacement for `Subject<T>` from Reactive Extensions (RX).

As a refresher, to use `Subject<T>` in Reactive Extensions (RX):

> Subject<int> subject = new Subject<int>();
	subject.Subscribe(message =>
	  {
		// Receives 42.
	  });
	subject.OnNext(42);

The new API is virtually identical:

> SubjectNetMQ<int> subject = new SubjectNetMQ<int>("tcp://127.0.0.1:56001");
	subject.Subscribe(message =>
	  {
		// Receives 42.
	  });
	subject.OnNext(42);

Currently, serialization is performed using ProtoBuf, so we have to annotate POCO classes with `ProtoContract` and `ProtoMember` like this:

> [ProtoContract]
	public struct MyMessage
	{
		[ProtoMember(1)]
		public int Num { get; set; }
		[ProtoMember(2)]
		public string Name { get; set; }
	}

To check out the demos, see:
- Publisher: Project `NetMQ.ReactiveExtensions.SamplePublisher`
- Subscriber: Project `NetMQ.ReactiveExtensions.SampleSubscriber`
- Sample unit tests: Project `NetMQ.ReactiveExtensions.Tests`

Notes:
- Compatible with all existing RX code. Can use `.Where()`, `.Select()`, etc.
- Runs at 120,000 messages per second on localhost.
- Supports `.OnNext()`, `.OnException()`, and `.OnCompleted()`.
- Properly passes exceptions across the wire.
- Supported by many unit tests.

### CODE REVIEW

**Comment by somdoron** [comment]
Do you want to add this as separate repository at https://github.com/netmq/
?

Let me know if you want, i will give you owner rights on the organization
to create try the repository.

**Comment by sharpe5** [comment]
Thanks, if you can give me owner rights I can create a NuGet package for NetMQ.ReactiveExtensions.

**Comment by somdoron** [comment]
I sent you an invite to the netmq organization. You can now create the ReactiveExtensions. You don't need any permission to create any nuget package, just create.

**Comment by sharpe5** [comment]
Thanks! Just created: 

https://github.com/NetMQ/NetMQ.ReactiveExtensions

**Comment by somdoron** [comment]
Great! Can we close this PR and move it to the new repository?

**Comment by sharpe5** [comment]
Sure. I'm going to have to follow the learning curve to convert this into a NuGet package, etc. I only have a few hours a week to work on this (6 month olds take up so much time!), so it may be a while before I can complete this.

**Comment by sharpe5** [comment]
@somdoron Run out of time tonight, but managed to get all of the sample code up, plus a (less than optimal) but usable Readme:

https://github.com/NetMQ/NetMQ.ReactiveExtensions

It's just sample code at the moment, and not in a NuGet package, any contributions and/or cleanup is welcome.

**Comment by drewnoakes** [comment]
@sharpe5 creating a NuGet package is pretty straightforward.

First, make a `.nuspec` file. You can copy the NetMQ one for starters.

Then, build (in Release mode).

    nuget pack YourFile.nuspec -Version 1.2.3
    nuget push YourFile.1.2.3.nupkg

You may need to set up your NuGet API key before this, but IIRC the tool explains how to do this or you can find it easily enough online.

The RX stuff looks good!

**Comment by sharpe5** [comment]
@drewnoakes Excellent, this sounds easier than I thought it was going to be. It might take me a few days before I can find time to get this up. This is my first foray into github, and it's turning out to be quite fun!

**Pull request closed without merging**
