### PR TITLE
Upgrade AsyncIO version to 0.1.61

### PR DESCRIPTION
**Pull request by dungpa**
Related to #767.
I upgrade AsyncIO version to 0.1.61. 
Unit tests seem to pass.

### CODE REVIEW

**Comment by dungpa** [comment]
@somdoron: Could you have a look at the changes please?

**Comment by somdoron** [comment]
Merged. Thanks

**Comment by dungpa** [comment]
@somdoron If you could find some time to publish a new NetMQ version using AsyncIO 0.1.61, that would be great. Thanks.

**Comment by somdoron** [comment]
I will try tomorrow.

**Comment by dungpa** [comment]
@somdoron Any luck on pushing a new NetMQ version?

**Comment by somdoron** [comment]
Just pushed:

https://www.nuget.org/packages/NetMQ/4.0.0.197-pre

Report back if the version works, I will test it as well.

If everything goes right I will mark it as stable

**Comment by dungpa** [comment]
Thanks. Will upgrade and report back.

**Comment by dungpa** [comment]
@somdoron The new version has been working for a couple of weeks. Thanks for the help.

**Pull request merged**
