### PR TITLE
Add DotNet core support

### LINKED ISSUE #497: Support .NET Core
We already have some .NET Core projects and we need this lib!

### PR DESCRIPTION
**Pull request by somdoron**
Fix #497

AppVeyor is not yet configured to build dotnet core, I will do that after the merge.

You can take a look here for passing tests:
https://ci.appveyor.com/project/somdoron/netmq-nk5mv

### CODE REVIEW

**Comment by drewnoakes** [comment]
> This folder contains more than one solution file

**Comment by drewnoakes** [comment]
BTW very cool that support for .NET Core is here!

**Comment by somdoron** [comment]
I will fix the CI tomorrow,  take a look at the link above for working CI.
Just need to change configuration a little to support core.

**Comment by drewnoakes** [comment]
Ok, I see that is what you meant in the original comment.

Very nice. Will be good when all this .NET Core stuff stabilises. Exciting to see NetMQ become a cross platform option.

**Comment by somdoron** [comment]
CI is working now, although some Poller tests are still flapping

**Pull request merged**
