### PR TITLE
Remove obsolete code

### LINKED ISSUE #450: problem: NetMQ is full of obsolete code
So the API is full of obsolete code, IMO that confusing and not elegant.

Suggested solution:
* Maintain NetMQ3-x repository with obsolete code
* This repository will become NetMQ4, with new nuget package
* We will remove obsolete code from NetMQ4 repository
* We will cherry pick bug fixes for NetMQ3-x
* NetMQ will be beta for sometime, after that we cannot delete methods
* Anything we remove from NetMQ4 we need to mark as obsolete in NetMQ3-x and provide the alternative

### PR DESCRIPTION
**Pull request by drewnoakes**
Remove all obsolete code.

Add square versions of project logo.

Some minor tidying.

Closes #450.

### CODE REVIEW

**Comment by somdoron** [comment]
So my only comment is that I thought to leave Poller,Scheduler and Context for a little while  more, so in a way everything we marked as obsolete will be removed in six month. So far I'm not sure users already familiar with new API.

**Comment by drewnoakes** [comment]
We definitely need a way to assist users in making the transition. As you say, few will be familiar with this new API, as many of the changes are currently only available in prerelease packages.

However users must consciously migrate from the `NetMQ` package to the `NetMQ4` package. In doing so, it seems reasonable to expect some breaking changes. We can make this process smooth however. The important thing is that users won't be surprised by sudden breakages by happily upgrading via NuGet -- they'll have to make a concious decision to upgrade.

Here is a draft of a migration guide.

Please especially check the point one in _How to upgrade?_ as it suggests an idea to perform a migration for users, whilst still allowing us to remove everything at once.

Let's discuss our approach here. Then when we have a plan, I'll move the text of this answer into a wiki page and link to it from the README.

----

# Migration from NetMQ version 3 to 4

NetMQ version 4 introduces some breaking changes for code migrated from version 3. These changes simplify the use of NetMQ, and the migration is not so difficult.

## Should I upgrade?

NetMQ version 3 will continue to receive bug fixes, but new features and improvements will be made to version 4 only. We expect most users will benefit from upgrading and encourage doing so.

## How to upgrade?

There are two approaches you may use:

1. Using NuGet, uninstall `NetMQ` from your project and install the `NetMQ4-migration` instead. This package generates compiler warnings about usages of obsolete APIs. The warnings will explain what changes are required. Once you're building without warnings, reference the latest stable `NetMQ4` package in order to receive bug fixes.

2. Bite the bullet and replace the `NetMQ` package with `NetMQ4` directly, and fix compilation errors.

---

# Changes

Much of the removed code have been marked `[Obsolete]` for several releases now, so many of the changes shown here are unlikely to apply to your code. Further, any one application is unlikely to depend upon much of the public API of NetMQ. Don't let the length of this list concern you.

For completeness, all API changes are detailed here.

## The context

`NetMQContext` has been removed. Previously you'd create one of these in your application and pass it around. NetMQ now manages this internally, making the API simpler.

Here's a comparison:

```csharp
// NetMQ version 3
using (var context = NetMQContext.Create())
using (var publisher = context.CreatePublisherSocket())
{
    // ...
}

// NetMQ version 4
using (var publisher = new PublisherSocket())
{
    // ...
}
```

Note the factory methods for sockets no longer exist. Instead, just call the constructor of the type you want to use.

- `NetMQContext.CreateRequestSocket()` :point_right: `new RequestSocket()`
- `NetMQContext.CreateResponseSocket()` :point_right: `new ResponseSocket()`
- `NetMQContext.CreateDealerSocket()` :point_right: `new DealerSocket()`
- `NetMQContext.CreateRouterSocket()` :point_right: `new RouterSocket()`
- `NetMQContext.CreateXPublisherSocket()` :point_right: `new XPublisherSocket()`
- `NetMQContext.CreatePairSocket()` :point_right: `new PairSocket()`
- `NetMQContext.CreatePushSocket()` :point_right: `new PushSocket()`
- `NetMQContext.CreatePublisherSocket()` :point_right: `new PublisherSocket()`
- `NetMQContext.CreatePullSocket()` :point_right: `new PullSocket()`
- `NetMQContext.CreateSubscriberSocket()` :point_right: `new SubscriberSocket()`
- `NetMQContext.CreateXSubscriberSocket()` :point_right: `new XSubscriberSocket()`
- `NetMQContext.CreateStreamSocket()` :point_right: `new StreamSocket()`
- `NetMQContext.CreateMonitorSocket()` :point_right: `new MonitorSocket()`

Further, constructors of the following classes no longer receive a context and calls should be updated:

- `NetMQForwarder`
- `NetMQBeacon`
- `QueueDevice`
- `StreamerDevice`
- `NetMQMonitor`

These factory methods no longer accept context instances:

- `NetMQActor.Create`

## Poller and Scheduler

The `Poller` and `NetMQScheduler` classes have been merged into the new `NetMQPoller` class.

- `Poller` :point_right: `NetMQPoller`

Adding and removing objects to poll:

- `Poller.AddSocket` :point_right: `NetMQPoller.Add`
- `Poller.AddTimer` :point_right: `NetMQPoller.Add`
- `Poller.AddPollInSocket` :point_right: `NetMQPoller.Add`
- `Poller.RemoveSocket` :point_right: `NetMQPoller.Remove`
- `Poller.RemoveTimer` :point_right: `NetMQPoller.Remove`
- `Poller.RemovePollInSocket` :point_right: `NetMQPoller.Remove`

Starting and stopping the poller.

- `Poller.PollTillCancelled` :point_right: `NetMQPoller.Run`
- `Poller.PollTillCancelledNonBlocking` :point_right: `NetMQPoller.RunAsync`
- `Poller.Cancel` :point_right: `NetMQPoller.Stop`
- `Poller.CancelNonBlocking` :point_right: `NetMQPoller.StopAsync`

Scheduling for the TPL:

- `NetMQScheduler` :point_right: `NetMQPoller`

By changing the `Add*` names to all be the same as simply `Add`, and by implementing `IEnumerable`, `NetMQPoller` now supports collection initialiser syntax:

```csharp
new NetMQPoller { publisher, subscriber, timer, tcpSocket }
```

`NetMQPoller` now implements `ISynchronizeInvoke` (and continues extending `TaskScheduler`), so it can be used to get schedule and synchronise work on the poller's thread from both the TPL and earlier BCL APIs.

## Receiving

Receiving a single frame using `Msg`:

- `IReceivingSocket.Receive(ref Msg, SendReceiveOptions)` :point_right:
  - `Receive(ref Msg)`
  - `TryReceive(ref Msg, TimeSpan) : bool`

Receiving a single frame as a `byte[]`:

- `IReceivingSocket.Receive() : byte[]`
- `IReceivingSocket.Receive(out bool) : byte[]`
- `IReceivingSocket.Receive(bool, out bool) : byte[]`
- `IReceivingSocket.Receive(SendReceiveOptions) : byte[]` 
- `IReceivingSocket.Receive(SendReceiveOptions, out bool) : byte[]` 
- `IReceivingSocket.Receive(TimeSpan) : byte[]` :point_right:
  - `ReceiveFrameBytes(): byte`
  - `ReceiveFrameBytes(out bool): byte`
  - `TryReceiveFrameBytes(out byte[]) : bool`
  - `TryReceiveFrameBytes(out byte[], out bool) : bool`
  - `TryReceiveFrameBytes(TimeSpan, out byte[]) : bool`
  - `TryReceiveFrameBytes(TimeSpan, out byte[], out bool) : bool`

Receiving an entire multipart message as `List<byte[]>`:

- `IReceivingSocket.ReceiveMessages() : List<byte[]>(int)`
- `IReceivingSocket.ReceiveAll() : List<byte[]>(int)` :point_right:
  - `IReceivingSocket.ReceiveMultipartBytes(int) : List<byte[]>`
  - `IReceivingSocket.ReceiveMultipartBytes(ref List<byte[]>, int): void`
  - `IReceivingSocket.TryReceiveMultipartBytes(ref List<byte[]>, int): bool`
  - `IReceivingSocket.TryReceiveMultipartBytes(TimeSpan, ref List<byte[]>, int): bool`

Receiving a single frame as a `string`:

- `IReceivingSocket.ReceiveString() : string`
- `IReceivingSocket.ReceiveString(SendReceiveOptions) : string`
- `IReceivingSocket.ReceiveString(SendReceiveOptions, out bool) : string`
- `IReceivingSocket.ReceiveString(Encoding) : string`
- `IReceivingSocket.ReceiveString(Encoding, SendReceiveOptions) : string`
- `IReceivingSocket.ReceiveString(Encoding, SendReceiveOptions, out bool) : string`
- `IReceivingSocket.ReceiveString(out bool) : string`
- `IReceivingSocket.ReceiveString(bool, out bool) : string`
- `IReceivingSocket.ReceiveString(TimeSpan) : string`
- `IReceivingSocket.ReceiveString(Encoding, out bool) : string`
- `IReceivingSocket.ReceiveString(Encoding, bool, out bool) : string`
- `IReceivingSocket.ReceiveString(Encoding, TimeSpan) : string` :point_right:
  - `IReceivingSocket.ReceiveFrameString() : string`
  - `IReceivingSocket.ReceiveFrameString(out bool) : string`
  - `IReceivingSocket.ReceiveFrameString(Encoding) : string`
  - `IReceivingSocket.ReceiveFrameString(Encoding, out bool) : string`
  - `IReceivingSocket.TryReceiveFrameString(out string) : bool`
  - `IReceivingSocket.TryReceiveFrameString(out string, out bool) : bool`
  - `IReceivingSocket.TryReceiveFrameString(Encoding, out string) : bool`
  - `IReceivingSocket.TryReceiveFrameString(Encoding, out string, out bool) : bool`
  - `IReceivingSocket.TryReceiveFrameString(TimeSpan, out string) : bool`
  - `IReceivingSocket.TryReceiveFrameString(TimeSpan, out string, out bool) : bool`
  - `IReceivingSocket.TryReceiveFrameString(TimeSpan, Encoding, out string) : bool`
  - `IReceivingSocket.TryReceiveFrameString(TimeSpan, Encoding, out string, out bool) : bool`

Receiving an entire multipart message as `List<string>`:

- `IReceivingSocket.ReceiveStringMessages(int) : List<string>`
- `IReceivingSocket.ReceiveStringMessages(Encoding, int) : List<string>`
- `IReceivingSocket.ReceiveAllString() : List<string>` :point_right:
  - `IReceivingSocket.ReceiveMultipartStrings() : List<string>`
  - `IReceivingSocket.ReceiveMultipartStrings(out bool) : List<string>`
  - `IReceivingSocket.TryReceiveMultipartStrings(ref List<string>, int) : bool`
  - `IReceivingSocket.TryReceiveMultipartStrings(Encoding, ref List<string>, int) : bool`
  - `IReceivingSocket.TryReceiveMultipartStrings(TimeSpan, ref List<string>, int) : bool`
  - `IReceivingSocket.TryReceiveMultipartStrings(TimeSpan, Encoding, ref List<string>, int) : bool`

Receiving an entire multipart message as `NetMQMessage`:

- `IReceivingSocket.ReceiveMessage(bool) : NetMQMessage`
- `IReceivingSocket.ReceiveMessage(NetMQMessage, bool) : void`
- `IReceivingSocket.ReceiveMessage(TimeSpan) : NetMQMessage` :point_right:
  - `IReceivingSocket.ReceiveMultipartMessage(int) : NetMQMessage`
  - `IReceivingSocket.TryReceiveMultipartMessage(ref NetMQMessage, int): bool`
  - `IReceivingSocket.TryReceiveMultipartMessage(TimeSpan ref NetMQMessage, int): bool`

Receiving a signal:

- `IReceivingSocket.WaitForSignal() : bool` :point_right:
  - `IReceivingSocket.ReceiveSignal(): bool`
  - `IReceivingSocket.TryReceiveSignal(out bool): bool`
  - `IReceivingSocket.TryReceiveSignal(TimeSpan, out bool): bool`

The ability to skip a frame has been added:
  
- `IReceivingSocket.SkipFrame(): bool`
- `IReceivingSocket.SkipFrame(out bool): bool`
- `IReceivingSocket.TrySkipFrame(): bool`
- `IReceivingSocket.TrySkipFrame(out bool): bool`
- `IReceivingSocket.TrySkipFrame(TimeSpan): bool`
- `IReceivingSocket.TrySkipFrame(TimeSpan, out bool): bool`

As well as the ability to skip entire multipart messages, or the remainder of the current message when partially received:

- `IReceivingSocket.SkipMultipartMessage(): bool`
- `IReceivingSocket.TrySkipMultipartMessage(): bool`
- `IReceivingSocket.TrySkipMultipartMessage(TimeSpan): bool`

- `NetMQSocketEventArgs.ReceiveReady` :point_right: `NetMQSocketEventArgs.IsReadyToReceive`

## Sending

- `IOutgoingSocket.Send(ref Msg, SendReceiveOptions)` :point_right: 
  - `Send(ref Msg, bool)`
  - `TrySend(ref Msg, TimeSpan, bool)`

- `IOutgoingSocket.Send(byte[], int, SendReceiveOptions)`
- `IOutgoingSocket.Send(byte[], int, bool, bool)`
- `IOutgoingSocket.Send(byte[])`
- `IOutgoingSocket.SendMore(byte[], bool)`
- `IOutgoingSocket.SendMore(byte[], int, bool)` :point_right: 
  - `SendFrame(byte[], bool)`
  - `SendFrame(byte[], int, bool)`
  - `SendMoreFrame(byte[])`
  - `SendMoreFrame(byte[], int)`
  - `TrySendFrame(TimeSpan, byte[], bool)`
  - `TrySendFrame(TimeSpan, byte[], int, bool)`
  - `TrySendFrame(byte[], bool)`
  - `TrySendFrame(byte[], int, bool)`

- `IOutgoingSocket.Send(string, bool, bool)`
- `IOutgoingSocket.Send(string, Encoding, SendReceiveOptions)`
- `IOutgoingSocket.Send(string, Encoding, bool, bool)`
- `IOutgoingSocket.SendMore(string, bool)`
- `IOutgoingSocket.SendMore(string, Encoding, bool)` :point_right:
  - `SendFrame(string, bool)`
  - `SendMoreFrame(string)`
  - `TrySendFrame(TimeSpan, string, bool)`
  - `TrySendFrame(string, bool)`

- `IOutgoingSocket.SendMessage(NetMQMessage, bool)` :point_right:
  - `SendMultipartMessage(NetMQMessage)`
  - `TrySendMultipartMessage(NetMQMessage)`
  - `TrySendMultipartMessage(TimeSpan, NetMQMessage)`

- `NetMQSocketEventArgs.SendReady` :point_right: `NetMQSocketEventArgs.IsReadyToSend`

## Subscribe / Unsubscribe

The `Subscribe` and `Unsubscribe` methods have been pushed down the class hierarchy from `NetMQSocket` to only those subclasses to which subscription applies (`SubscriberSocket` and `XSubscriberSocket`). This shouldn't affect any correct code, but is mentioned here for completeness.

## Socket Options

Some unused socket options were removed:

- `ReceiveTimeout` (use overloads of `TryReceive` that accept a `TimeSpan`)
- `SendTimeout` (use overloads of `TrySend` that accept a `TimeSpan`)
- `TcpAcceptFilter`
- `TcpKeepaliveCnt`
- `CopyMessages`
- `ReceivevBuffer` :point_right: `ReceiveBuffer` (typo)
- `GetLastEndpoint` :point_right: `LastEndpoint`

## Exceptions

- `ErrorPollingException` was unused and has been removed
- `AgainException` is no longer used as send/receive methods use the `Try*` pattern and return `false` in case the operation would block 

## Error codes

Unused members of the `ErrorCode` enum have been removed.

- `ErrorCode.InProgres` :point_right: `ErrorCode.InProgress` (typo)
- `ErrorCode.ENOENT` :point_right: `ErrorCode.EndpointNotFound`
- `ErrorCode.EACCESS` :point_right: `ErrorCode.AccessDenied`
- `ErrorCode.EFAULT` :point_right: `ErrorCode.Fault`
- `ErrorCode.EINV` :point_right: `ErrorCode.Invalid`
- `ErrorCode.EAGAIN` :point_right: `ErrorCode.TryAgain`
- `ErrorCode.EINPROGRESS` :point_right: `ErrorCode.InProgress`
- `ErrorCode.EPROTONOSUPPORT` :point_right: `ProtocolNotSupported.`
- `ErrorCode.ENOTSUP ` :negative_squared_cross_mark: 
- `ErrorCode.EADDRINUSE` :point_right: `ErrorCode.AddressAlreadyInUse`
- `ErrorCode.EADDRNOTAVAIL` :point_right: `ErrorCode.AddressNotAvailable`
- `ErrorCode.ENETDOWN` :point_right: `ErrorCode.NetworkDown`
- `ErrorCode.ENOBUFS` :point_right: `ErrorCode.NoBufferSpaceAvailable`
- `ErrorCode.EISCONN` :negative_squared_cross_mark:
- `ErrorCode.EINTR` :negative_squared_cross_mark:
- `ErrorCode.ENOTCONN` :point_right: `ErrorCode.NotConnected`
- `ErrorCode.ECONNREFUSED` :point_right: `ErrorCode.ConnectionRefused`
- `ErrorCode.EHOSTUNREACH` :point_right: `ErrorCode.HostUnreachable`
- `ErrorCode.ZMQ_HAUSNUMERO` :point_right: `ErrorCode.BaseErrorNumber`
- `ErrorCode.EMSGSIZE` :point_right: `ErrorCode.MessageSize`
- `ErrorCode.EAFNOSUPPORT` :point_right: `ErrorCode.AddressFamilyNotSupported`
- `ErrorCode.ENETUNREACH` :point_right: `ErrorCode.NetworkUnreachable`
- `ErrorCode.ECONNABORTED` :point_right: `ErrorCode.ConnectionAborted`
- `ErrorCode.ECONNRESET` :point_right: `ErrorCode.ConnectionReset`
- `ErrorCode.ETIMEDOUT` :point_right: `ErrorCode.TimedOut`
- `ErrorCode.ENETRESET` :point_right: `ErrorCode.NetworkReset`
- `ErrorCode.EFSM` :point_right: `ErrorCode.FiniteStateMachine`
- `ErrorCode.ENOCOMPATPROTO` :negative_squared_cross_mark:
- `ErrorCode.ETERM` :point_right: `ErrorCode.ContextTerminated`
- `ErrorCode.EMTHREAD` :point_right: `ErrorCode.EmptyThread`
- `ErrorCode.EIOEXC` :negative_squared_cross_mark:
- `ErrorCode.ESOCKET` :negative_squared_cross_mark:
- `ErrorCode.EMFILE` :point_right: `ErrorCode.TooManyOpenSockets`

## Miscellaneous

The following items have been obsolete for a long time and their use is very unlikely if you observe compiler warnings. However they are listed here for completeness.

- `Blob` :point_right: `NetMQFrame`
- `Actor<T>` :point_right: `NetMQActor` (non-generic)
- `IShimHandler<T>` :point_right: `IShimHandler` (non-generic)
- `ActorKnownMessages.END_PIPE` :point_right: `NetMQActor.EndShimMessage`
- enum `MsgType.Invalid` :point_right: `MsgType.Uninitialised`
- `MsgType.Check()` :point_right: `MsgType.IsInitialised`
- `SocketEvent` :point_right: `SocketEvents`

**Comment by somdoron** [comment]
Wow, great work!

Only one comment, I think instead of making a migration version, we should just say, if you using v3 without obsolete warning you can upgrade safely. We need to make sure everything we remove we first mark as obsolete on the v3.

**Comment by somdoron** [comment]
Do you want to make a file out of your comment and link it from the main page?

**Comment by drewnoakes** [comment]
@somdoron yes that seems simple enough. So we should now make (non pre-release) releases of v3 and v4, with and without obsolete code respectively.

Yeah I'll pull that markdown into a new wiki page and update the text based on your idea.

**Comment by drewnoakes** [comment]
It's updated and on the wiki: https://github.com/zeromq/netmq/wiki/Migrating-to-v4

**Pull request merged**
