### PR TITLE
removed JetBrains.Anotations

### PR DESCRIPTION
**Pull request by awb99**
and added Compiled AsyncIO into lib folder

### CODE REVIEW

**Comment by awb99** [comment]
As to AsyncIO project: One can tell github to include the full sourcecode of another project when the pull is done. I have seen this onother projects in the past. Unfortunatley Idont know how to do it myself.

**Comment by drewnoakes** [comment]
Hi. Could you explain the rationale for removing `JetBrains.Annotations`, and also for not using NuGet for the AsyncIO dependency? Git's not idea for storing binaries. I think the process you're describing is git submodules, which are a possibility.

Are you experiencing a problem from the annotations dependency? It's not required at runtime -- only at compile time, as far as I know.

**Comment by awb99** [comment]
If I have to recompile the solution a SubModule is much better; say I have to use a different library version; then with submodules this works much better.

In some other Issue I read that this is what someone asked to be done. I have compiled the solution with SharpDevelop and did not see any NuGet references. So I thought you have this somewhere in your build server. Without the JetBrain annotations library it would not compile.

**Comment by drewnoakes** [comment]
It just sounds like your NuGet package restore is broken.

What version of NuGet are you using? I'm on 3.2.0.10516.

Are you using Mono?

**Comment by tobi-tobsen** [comment]
I don't like the SubModule approach. Lets keep using nuget instead of git magic to pull unbuilt dependencies.

**Comment by awb99** [comment]
I am using SharpDevelop on Windows; but I run the binaries on Mono. It seems SharpDeveop has some issues with NuGet. But the final dlls work perfect on Mono!! Amazing! Microsoft.Remoting Channels do not work on Mono for example.

**Comment by somdoron** [comment]
great news. @awb99 is it ok if we close this PR and not merging, I think we pretty happy with nuget managing our dependencies and resharper annotations

**Comment by awb99** [comment]
of course!

**Pull request closed without merging**
