### PR TITLE
Migrated handling of Z85 encoding

### PR DESCRIPTION
**Pull request by dxdjgl**

### CODE REVIEW

**Comment by somdoron** [comment]
Very nice

**Comment by dxdjgl** [comment]
@somdoron would it be possible to have a build made and also a build of Nacl.net as well? Sorry for bugging you.

**Comment by somdoron** [comment]
@dxdjgl just released a nacl version, if you can update NetMQ to use the latest version and I  will merge it.

Also, if you would to join NetMQ maintainer that will be great, read our collaboration model here and let me know if you would like to join:
https://rfc.zeromq.org/spec/42/

**Comment by somdoron** [comment]
https://www.nuget.org/packages/NaCl.Net/0.1.12

**Comment by dxdjgl** [comment]
@somdoron thank you very much for building the software. Regarding joining the NetMQ maintainer, what kind of commitment is expected. With a hectic everyday life work and private, I cannot commit to specific targets, however I am willing to pitch in from time to time, when my schedule allows it.

**Comment by somdoron** [comment]
It is mainly reviewing and merging pull requests. The project is pretty stable, so that is not much at the moment.

**Comment by somdoron** [comment]
Make sure not to merge your own, though.

Anyway I released a new pre-release version, it should be on nuget in a couple of minutes.

**Comment by dxdjgl** [comment]
Sign me up, and sure its not good practice to merge your own code.

**Comment by somdoron** [comment]
https://www.nuget.org/packages/NetMQ/4.0.1.3-pre

**Pull request merged**
