### PR TITLE
 Rename variable name from 'i' to 'dstOffset'

### PR DESCRIPTION
**Pull request by moreal**
I think the name 'i' is not good for understanding the purpose of the variable

### CODE REVIEW

**Comment by moreal** [comment]
I need your feedback :+1:

**Comment by somdoron** [comment]
Thanks

**Comment by drewnoakes** [comment]
잘 했어

**Comment by moreal** [comment]
@drewnoakes
감사합니다 :D
Thank you :D

**Comment by drewnoakes** [comment]
아닙니다 :)

**Pull request merged**
