### PR TITLE
Breaking change: add params args to IShimHandler. Issue #475

### PR DESCRIPTION
**Pull request by dalebrubaker**

### CODE REVIEW

**Comment by somdoron** [comment]
I don't think to make breaking change...

**Comment by dalebrubaker** [comment]
Okay. This is what it would have looked like. Ref Issue #475 discussion.
So you can reject this PR...

**Comment by dalebrubaker** [comment]
Actually, I think I see an easier way to make this not-breaking, so don't reject it yet. Thanks.

**Comment by somdoron** [comment]
So my idea at the time was to just accept it as constructor parameter.
this is why I didn't not include it in the actor.
So you have to implement IShimHandler, in the class that implement just take a parameter. Save it in constructor and the Run method can use it.

**Comment by dalebrubaker** [comment]
That works, thank you. Closing this PR.

**Pull request closed without merging**
