### PR TITLE
Majordomo Protocol extended for service discovery

### PR DESCRIPTION
**Pull request by mph911**
extended Majordomo for service discovery
added a BAT file for starting the example

-> if this is not mergable could someone tell me what to do? I am not tooooo experienced with GuítHub!

Thank you very much indeed!
Peter

### CODE REVIEW

**Comment by drewnoakes** [comment]
Hey Peter, just taking a look at this now. Seems to be based off some old code which is preventing the merge. To make it merge-able, you may have to rebase on top of the latest master branch and resolve any conflicts. Let me know if you need any help with that.

**Comment by drewnoakes** [comment]
So yeah, I took a look through and there are some great improvements here. I'm a big fan of the MDP work you've been doing. Would you like me to re-work these commits so they don't conflict? I'd probably exclude the project version number changes unless you feel they're important for some reason.

**Comment by mph911** [comment]
Hi Drew,

I’ve added the version numbers just as a habit – no specific reasons other than that I’m doing it on all projects I work on. So feel free to remove and YES you would do me a big favour if you could re-work the commits.

Shall I pull the merged version than?

I am working on TITANIC pattern right now and plan do work on CLONE than.

You wrote that I am using an old code base. Which one is the current one?

And thank you for the encouraging word in regard to the MDP ☺ and I am happy if I can contribute something to this superb project! KUDOS!
Peter

Von: Drew Noakes [mailto:notifications@github.com]
Gesendet: Samstag, 7. März 2015 19:26
An: zeromq/netmq
Cc: P. H. Merkel (MerkelConsult)
Betreff: Re: [netmq] Majordomo Protocol extended for service discovery (#285)


So yeah, I took a look through and there are some great improvements here. I'm a big fan of the MDP work you've been doing. Would you like me to re-work these commits so they don't conflict? I'd probably exclude the project version number changes unless you feel they're important for some reason.

**Comment by drewnoakes** [comment]
Hi Peter,

Looking at this now and will get it merged in shortly.

> You wrote that I am using an old code base. Which one is the current one?

It's the same code base--however the project's `master` branch had moved on from the point you last worked at. This means that your pull request's branch forks off from the official NetMQ repository some time ago in the history, and that your changes are more likely to conflict.

> Shall I pull the merged version than?

In general I would suggest avoiding the use of `git pull`. It's much clearer to see what's going on if you do a `git fetch origin` [1], then run a graphical visualiser (`gitk --all` is quite good, but you may find another more friendly) to see what's going on.

Once you see the situation, you can `rebase` or `reset` accordingly.

Everyone has a different git workflow though :)

> I am working on TITANIC pattern right now

Sounds great!

---

[1] this assumes that you use `origin` as the name of the official NetMQ repository remote. If you're unsure, run:

```text
$ git remote -v
mph911  git://github.com/mph911/netmq.git (fetch)
mph911  git://github.com/mph911/netmq.git (push)
origin  git@github.com:zeromq/netmq.git (fetch)
origin  git@github.com:zeromq/netmq.git (push)
...
```

See here that I have two remotes, one for NetMQ (`origin`) and one for your repo (`mph911`).

If your output looks different and you'd like some help, let me know.

**Comment by drewnoakes** [comment]
Thanks. It's pushed in 51a73b706499673c71df7fb06a4c6ead9d43c9e8.

**Comment by mph911** [comment]
================== REPLY / ANTWORT ================================================

Hi Drew,

Thank you for the advise! ☺

Now here is my situation:

·         I forked the project some time ago

·         If I do a fetch I can not find any new stuff. I think because the repo I am fetching against is the original fork.

Do I have to refork the repo again? And if so, how do I delete the old fork on GitHub?
And if not, how do I update the fork on GitHub?

Any advise would be greatly apreciated, since I do not want to work of an ‘outdated’ version of NetMQ!

Since I have never done this before I am a bit lost! ☹ Sorry for bugging you!

Cheers,

Merkel, Peter
_____________________________
Diese Information ist ausschließlich für die adressierte Person oder Organisation bestimmt und könnte vertrauliches und/oder privilegiertes Material enthalten. Personen oder Organisationen, für die diese Information nicht bestimmt ist, ist es nicht gestattet, diese zu lesen, erneut zu übertragen, zu verbreiten, anderweitig zu verwenden oder sich durch sie veranlasst zu sehen, Maßnahmen irgendeiner Art zu ergreifen. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender in Verbindung zu setzen und das Material von Ihrem Computer zu löschen. Sie haben uns gebeten, mit Ihnen über das Internet per E-Mail zu korrespondieren. Unbeschadet dessen ist allein die von uns unterzeichnete schriftliche Fassung verbindlich. Wir weisen darauf hin, dass derartige Nachrichten mit und ohne Zutun von Dritten verloren gehen, verändert oder verfälscht werden können. Herkömmliche E-Mails sind nicht gegen den Zugriff von Dritten geschützt und deshalb ist auch die Vertraulichkeit unter Umständen nicht gewahrt Wir haften deshalb nicht für die Unversehrtheit von E-Mails nachdem sie unseren Herrschaftsbereich verlassen haben und können Ihnen hieraus entstehende Schäden nicht ersetzen. Sollte trotz der von uns verwendeten Virus-Schutz-Programmen durch die Zusendung von E-Mails ein Virus in Ihre Systeme gelangen, haften wir nicht für eventuell hieraus entstehende Schäden. Dieser Haftungsausschluss gilt nur soweit gesetzlich zulässig.
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer. You have asked us to correspond with you via the Internet per e-mail. However, the written version signed by us is the only authoritative version. We draw your attention to the fact that such messages can be lost, changed or falsified, with or without any interference by third persons. Normal e-mails are not protected against access by third persons and, therefore, their confidentiality may not be assured in certain circumstances. We cannot be responsible for the integrity of emails after they have left our sphere of control. We shall not, therefore, indemnify you for any damages resulting out of these circumstances. If, despite our use of anti-virus software, a virus enters your systems in connection with the sending of the e-mail, you may not hold us liable for any damages that may possibly arise in that connection. We will accept liability which by law we cannot exclude.

Von: Drew Noakes [mailto:notifications@github.com]
Gesendet: Sonntag, 8. März 2015 19:10
An: zeromq/netmq
Cc: P. H. Merkel (MerkelConsult)
Betreff: Re: [netmq] Majordomo Protocol extended for service discovery (#285)


Hi Peter,

Looking at this now and will get it merged in shortly.

You wrote that I am using an old code base. Which one is the current one?

It's the same code base--however the project's master branch had moved on from the point you last worked at. This means that your pull request's branch forks off from the official NetMQ repository some time ago in the history, and that your changes are more likely to conflict.

Shall I pull the merged version than?

In general I would suggest avoiding the use of git pull. It's much clearer to see what's going on if you do a git fetch origin [1], then run a graphical visualiser (gitk --all is quite good, but you may find another more friendly) to see what's going on.

Once you see the situation, you can rebase or reset accordingly.

Everyone has a different git workflow though :)

I am working on TITANIC pattern right now

Sounds great!

________________________________

[1] this assumes that you use origin as the name of the official NetMQ repository remote. If you're unsure, run:

$ git remote -v

mph911  git://github.com/mph911/netmq.git (fetch)

mph911  git://github.com/mph911/netmq.git (push)

origin  git@github.com:zeromq/netmq.git<mailto:git@github.com:zeromq/netmq.git> (fetch)

origin  git@github.com:zeromq/netmq.git<mailto:git@github.com:zeromq/netmq.git> (push)

...

See here that I have two remotes, one for NetMQ (origin) and one for your repo (mph911).

If your output looks different and you'd like some help, let me know.

**Comment by drewnoakes** [comment]
@mph911, I am guessing that you pressed the 'fork' button on GitHub a while ago, and cloned your fork. Note that commits pushed to the main NetMQ project don't automatically appear in your fork. It's up to you to fetch them from NetMQ (let's call that _upstream_) and push them to your fork (let's call that _origin_).

What is the output of the following on your command line?

    git remote -v

If my psychic powers are doing their job, it should show (note the `mph911` in particular):

```text
origin  git://github.com/mph911/netmq.git (fetch)
origin  git://github.com/mph911/netmq.git (push)
```

If that's the case, then try the following. Add the main NetMQ project as a remote called _upstream_ (note the `zeromq` this time):

    git remote add upstream git@github.com:zeromq/netmq.git

Fetch from that remote:

    git fetch upstream

Once you've done that, you can look and see what state your branches are in, then rebase/reset accordingly.

**Comment by mph911** [comment]
Let me tell you that your psychic powers are amazing. Did as I was told and it seems to have worked 😊

Von meinem Windows Phone gesendet
________________________________
Von: Drew Noakes<mailto:notifications@github.com>
Gesendet: ‎09.‎03.‎2015 23:58
An: zeromq/netmq<mailto:netmq@noreply.github.com>
Cc: P. H. Merkel (MerkelConsult)<mailto:pm@merkelconsult.net>
Betreff: Re: [netmq] Majordomo Protocol extended for service discovery (#285)


@mph911<https://github.com/mph911>, I am guessing that you pressed the 'fork' button on GitHub a while ago, and cloned your fork. Note that commits pushed to the main NetMQ project don't automatically appear in your fork. It's up to you to fetch them from NetMQ (let's call that upstream) and push them to your fork (let's call that origin).

What is the output of the following on your command line?

git remote -v


If my psychic powers are doing their job, it should show (note the mph911 in particular):

origin  git://github.com/mph911/netmq.git (fetch)
origin  git://github.com/mph911/netmq.git (push)


If that's the case, then try the following. Add the main NetMQ project as a remote called upstream (note the zeromq this time):

git remote add upstream git@github.com:zeromq/netmq.git


Fetch from that remote:

git fetch upstream


Once you've done that, you can look and see what state your branches are in, then rebase/reset accordingly.

**Pull request closed without merging**
