### PR TITLE
Add logo. Use in README and nuspec file.

### PR DESCRIPTION
**Pull request by drewnoakes**
I think the URLs are correct, but will only be able to reliably test if merged.

For NuGet, there's an ICO as described in #242.

There are a few versions of the logo as PNG, as they may come in handy in future.

### CODE REVIEW

**Comment by somdoron** [comment]
seems github doesn't support svg hosting, you can use https://rawgit.com/

**Comment by drewnoakes** [comment]
Hmm. Seems githubusercontent serves SVG with MIME `text/plain`.

**Comment by drewnoakes** [comment]
Thanks. Should I make another PR or just edit the file directly?

**Comment by somdoron** [comment]
just edit, text you can edit directly. for source code we do pull requests

**Comment by drewnoakes** [comment]
Seems sensible.

Done!

**Comment by somdoron** [comment]
awesome!!!

**Comment by somdoron** [comment]
@drewnoakes do you have a twitter?

**Comment by drewnoakes** [comment]
Yes, it's @drewnoakes

**Pull request merged**
