### PR TITLE
Manual context termination

### PR DESCRIPTION
**Pull request by dgsantana**
This pull request, adds the ability to terminate and create the global NetMQ context. For this to happen a ManualTerminationTakeOver, must be called at least once. After this the developer is responsible for the life time control of the NetMQ context.
This is a requirement for Unity3D development where the Editor wasn't playing nice with the static global context, since after calling Play, the context isn't terminated (no application exit happens). This may also help in some extreme cases like using pythonnet with NetMQ inside a DCC app, like 3dsmax or maya, where there is need for more control over the life of the context.

### CODE REVIEW

**Comment by somdoron** [comment]
@dgsantana the CycleCreateTerminate test is hanging in the CI, can you check?

**Comment by dgsantana** [comment]
Found the cue, its after running the BeaconTest that the
CycleCreateTerminate fails, so something must be left after running that
test. I'm going to debug the test and post results here.

Doron Somech <notifications@github.com> escreveu no dia segunda, 2/05/2016
às 16:16:

**Comment by dgsantana** [comment]
Going a bit deeper, Beacon causes any blocking context termination to .
When waiting for the termination maibox to receive the Command.Done, the
signaler Wait never returns.

Daniel Santana <danielgsantana@gmail.com> escreveu no dia segunda,
2/05/2016 às 17:53:

**Comment by somdoron** [comment]
So beacon... I will also give it a look

**Pull request merged**
