### PR TITLE
multitarget netstandard2.0

### PR DESCRIPTION
**Pull request by valeriob**

### CODE REVIEW

**Comment by iiwaasnet** [comment]
Is there any code, which works only on net40 or we can have just netstandard2.0?

**Comment by valeriob** [comment]
I'm trying to solve the issue https://github.com/dotnet/project-system/issues/4252  following  the guidance from the .net team.
But i have no clue why it failed :(

**Comment by valeriob** [comment]
upgrading System.ServiceModel.Primitives to 4.3.0 solves my issue too !!!

4>Writing lock file to disk. Path: C:\Dev\netmq\src\NetMQ\obj\project.assets.json
4>Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version. 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0) 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Net.NameResolution (>= 4.0.0)
4>Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.Primitives (>= 4.3.0) 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Net.Primitives (>= 4.0.11)
4>Detected package downgrade: System.Security.Principal.Windows from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version. 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Security.Principal.Windows (>= 4.3.0) 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Security.Principal.Windows (>= 4.0.0)
4>Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Text.Encoding.Extensions (>= 4.3.0) 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Xml.ReaderWriter 4.0.11 -> System.Text.Encoding.Extensions (>= 4.0.11)
4>Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Net.Http 4.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Text.Encoding.Extensions (>= 4.3.0) 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Text.Encoding.Extensions (>= 4.0.11)
4>Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.IO.FileSystem 4.3.0 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Text.Encoding.Extensions (>= 4.3.0) 
4> OnRtls -> NetMQ -> System.ServiceModel.Primitives 4.1.0 -> System.Private.ServiceModel 4.1.0 -> System.Text.Encoding.Extensions (>= 4.0.11)
4>Committing restore...

**Comment by valeriob** [comment]
Hi, 
can you tell me why the build fails ? I did run tests on my machine and they all passed.
Thanks

**Comment by somdoron** [comment]
thanks.

**Comment by valeriob** [comment]
Thanks @somdoron 
would you mind to publish a pre-release package too ? 😄

**Pull request merged**
