### PR TITLE
Fixed a few typos

### PR DESCRIPTION
**Pull request by sean-gilliam**
Most of them were in the xmldocs and comments

### CODE REVIEW

**Comment by JamesWHurst** [comment]
All good corrections - how did you find all these?  I do think spelling is good to have correct - it helps the clarity of the comments. I ran a spelling-checker (VSSpellChecker, a VS plugin) recently - wonder why it missed these?

**Comment by drewnoakes** [comment]
Thanks!

**Comment by sean-gilliam** [comment]
@JamesWHurst [ReSpeller] (https://resharper-plugins.jetbrains.com/packages/ReSpeller/)

**Comment by JamesWHurst** [comment]
Thank you Sean - I'll start trying this instead. VSSpellChecker did nothing but embarrass me.

**Pull request merged**
