### PR TITLE
Fix for #739 - reference counting leading to bad data race condition

### PR DESCRIPTION
**Pull request by Amarok79**
See #739.

I only upload the PR.

Kudos goes to @livermana for finding and fixing the issue.

### CODE REVIEW

**Comment by Amarok79** [comment]
Hmm, the build errors seem unrelated to my changes.

@somdoron Can you please have a look?

**Comment by somdoron** [comment]
I will review this tomorrow...

**Comment by Amarok79** [comment]
@somdoron 

I updated the PR so that checks become green. Do you mind including the PR into your mainline? I can tell after one year of usage that @livermana's original fix works as expected.

**Comment by somdoron** [comment]
@Amarok79 there indeed a bug, but this fix miss one case, where the message was already shared, (you can reproduce by calling Msg.Copy). Anyway, I suggest the following fix:

https://github.com/zeromq/netmq/pull/844

**Comment by somdoron** [comment]
Closing, #844 fixes same problem

**Pull request closed without merging**
