### PR TITLE
problem: developing peer to peer with current socket is hard

### PR DESCRIPTION
**Pull request by somdoron**
you have to use a dealer socket for every connection you made.

With peer socket type, you can get routing id of the peer you just connected to and use one socket both for incoming connections and outgoing connections.

### CODE REVIEW

**Comment by somdoron** [comment]
@drewnoakes can you merge?

**Comment by somdoron** [comment]
@c-rack can you please merge?

**Comment by c-rack** [comment]
Sure :)

**Comment by somdoron** [comment]
thanks

**Pull request merged**
