### PR TITLE
Issue #636: Fix unhandled Exception and handling when PGM Publisher and Subscribe…

### PR DESCRIPTION
**Pull request by leguanjoe**
…r are bound to same interface and network cable gets unplugged. This i a fix for Issue #636

### CODE REVIEW

**Comment by somdoron** [comment]
Why did you close it?

**Comment by leguanjoe** [comment]
Hi,

I saw that I can fix another issue, too, by just changing one line of code of my pull request.

Should I have triggered another pull request?

 

Best Regards

Timur Amiri
 

 

 
 

Gesendet: Donnerstag, 19. Januar 2017 um 14:28 Uhr
Von: "Doron Somech" <notifications@github.com>
An: zeromq/netmq <netmq@noreply.github.com>
Cc: leguanjoe <timur-amiri@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [zeromq/netmq] Issue #636: Fix unhandled Exception and handling when PGM Publisher and Subscribe… (#637)


Why did you close it?

**Comment by leguanjoe** [comment]
Hi again,

ok, I see. I could have added another commit to the same pull request. I wasn't aware of that. Actually this is my first pull request.


 

Best regards,

Timur Amiri

 

Gesendet: Donnerstag, 19. Januar 2017 um 14:28 Uhr
Von: "Doron Somech" <notifications@github.com>
An: zeromq/netmq <netmq@noreply.github.com>
Cc: leguanjoe <timur-amiri@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [zeromq/netmq] Issue #636: Fix unhandled Exception and handling when PGM Publisher and Subscribe… (#637)


Why did you close it?

**Comment by somdoron** [comment]
That fine

**Pull request closed without merging**
