### PR TITLE
Provision to have override long running poller 

### PR DESCRIPTION
**Pull request by AnandKR84**
Marking the Poller thread a background thread since the process hosting this poller is not shutting down.

### CODE REVIEW

**Comment by drewnoakes** [comment]
This will potentially break applications that currently depend upon the poller thread being a foreground thread.

**Comment by drewnoakes** [comment]
Are you not able to dispose the poller in your application to have graceful exit?

**Comment by AnandKR84** [comment]
> Are you not able to dispose the poller in your application to have graceful exit?

Yes, that is possible, but in cases where the poller is in a singleton class, we are finding this issue. (I know that singleton is an anti-pattern, but in our case, it is needed to be a singleton class.)

**Comment by drewnoakes** [comment]
Can you dispose your singleton as your `Main` method exits?

**Comment by drewnoakes** [comment]
This is a source-compatible change, but not a binary-compatible one.

@somdoron what's the bar we set for these kinds of changes? If someone updates the library without recompiling (e.g. imported as a transitive dependency) they'll get `MethodMissingException` at runtime. Do we need an overload, or perhaps a new property to control this?

**Comment by somdoron** [comment]
I think the solution is pretty simple, just to add another overload and it will binary compatible?

**Comment by drewnoakes** [comment]
@AnandKR84 can you update this PR to overload the method?

**Comment by somdoron** [comment]
@AnandKR84 any reason for closing the PR?

**Comment by AnandKR84** [comment]
> @AnandKR84 any reason for closing the PR?

It was by mistake that was done. There was some formatting changes since i did it in a new editor.

**Comment by dxdjgl** [comment]
I know it is a bit of nitpicking, but I dont like the name longRunningPoller, which also causes a negation inside RunAsync method.
I think I would prefer somehting like IsBackgroundThread, otherwise I am okay with the code now.

**Comment by dxdjgl** [comment]
@somdoron I think the code is fine now do you agree?

**Comment by dxdjgl** [comment]
Since the negation has gone, the the value passed in public void RunAsync(string threadName) must be changed as well.

@somdoron when this change has been applied, the I think it should be okay to be pulled?

**Comment by AnandKR84** [comment]
> Since the negation has gone, the the value passed in public void RunAsync(string threadName) must be changed as well.
> 
> @somdoron when this change has been applied, the I think it should be okay to be pulled?

Thanks @dxdjgl for pointing it out.

**Pull request merged**
