### PR TITLE
release buffer after processing

### PR DESCRIPTION
**Pull request by somdoron**

### CODE REVIEW

**Comment by somdoron** [comment]
ready to be merged

**Comment by somdoron** [comment]
@reiroldan or @krisrok and this as well

**Comment by ndextraze-pbp** [comment]
I'm getting PollTests failures after on master TC build after merging this pull request. Should I revert?

**Comment by somdoron** [comment]
It is a known isssue, the two timers test fail from time to time because it needs to be accurate. I need to fix the test somehow

**Pull request merged**
